accounts/urls.py
from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView, TemplateView, PasswordResetView, PasswordResetDoneView,\
    PasswordResetConfirmView, PasswordResetCompleteView, PasswordChangeView, PasswordChangeDoneView

from accounts import views

app_name = 'accounts'

urlpatterns = [

    path('home/', TemplateView.as_view(template_name='base.html'), name='home'),
    path('user_register/', views.UserCreationView.as_view(), name='registration'),
    path('student_register/', views.StudentCreationView.as_view(), name='student'),
    path('teacher_register/', views.TeacherCreationView.as_view(), name='teacher'),

    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('student/', views.StudentList.as_view(), name='student_list'),
    path('teacher/', views.TeacherList.as_view(), name='teacher_list'),

    path('student_detail/<int:pk>/', views.StudentDetail.as_view(), name='student_detail'),
    path('teacher_detail/<int:pk>/', views.TeacherDetail.as_view(), name='teacher_detail'),

    path('student_update/<int:pk>/', views.StudentUpdateView.as_view(), name='student_update'),
    path('teacher_update/<int:pk>/', views.TeacherUpdateView.as_view(), name='teacher_update'),

    path('student_new_update/<int:pk>/', views.StudentUpdateNewView.as_view(), name='student_new_update'),

    path('student_delete/<int:pk>/', views.StudentDeleteView.as_view(), name='student_delete'),
    path('teacher_delete/<int:pk>/', views.TeacherDeleteView.as_view(), name='teacher_delete')

]

neptune/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
"""Model for account users."""

from django.contrib.auth.models import AbstractUser
from django.db import models

from core.models import BaseModel

MALE = 'male'
FEMALE = 'female'
NOT_SPECIFIED = 'not specified'
GENDER_CHOICES = (
    (MALE, 'Male'),
    (FEMALE, 'Female'),
    (NOT_SPECIFIED, 'Not Specified'),
)

ONE = 1
TWO = 2
THREE = 3
FOUR = 4
FIVE = 5
SIX = 6
SEVEN = 7
EIGHT = 8
NINE = 9
TEN = 10
ELEVEN = 11
TWELVE = 12

SATANDARD_CHOICE = (
    (ONE, 1),
    (TWO, 2),
    (THREE, 3),
    (FOUR, 4),
    (FIVE, 5),
    (SIX, 6),
    (SEVEN, 7),
    (EIGHT, 8),
    (NINE, 9),
    (TEN, 10),
    (ELEVEN, 11),
    (TWELVE, 12),
)

A = 'a'
B = 'b'
C = 'c'
D = 'd'
E = 'd'
F = 'f'
G = 'g'
H = 'h'

DIVISION_CHOICE = (
    (A, 'a'),
    (B, 'b'),
    (C, 'c'),
    (D, 'd'),
    (E, 'd'),
    (F, 'f'),
    (G, 'g'),
    (H, 'h'),
)

ONGOING = 'ongoing'
COMPLETED = 'completed'
DROPPED = 'dropped'
STATUS_CHOICES = (
    (ONGOING, 'Ongoing'),
    (COMPLETED, 'Completed'),
    (DROPPED, 'Dropped'),
)

DIPLOMA = 'diploma'
GRADUATE = 'graduate'
POSTGRADUATE = 'postgraduate'
DOCTOR_OF_PHILOSOPHY = 'doctor-of-philosophy'
POSTDOCTORAL_RESEARCHER = 'postdoctoral-researcher'
OTHER = 'other'
COURSE_TYPE_CHOICES = (
    (DIPLOMA, 'Diploma'),
    (GRADUATE, 'Graduate'),
    (POSTGRADUATE, 'Postgraduate'),
    (DOCTOR_OF_PHILOSOPHY, 'Doctor of Philosophy'),
    (POSTDOCTORAL_RESEARCHER, 'Postdoctoral researcher'),
    (OTHER, 'Other')
)


class User(AbstractUser):
    """Create users using AbstractUser."""

    profile_picture = models.ImageField(
        blank=True, null=True, upload_to='accounts/user/profile-picture')
    birth_date = models.DateField(blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    gender = models.CharField(
        max_length=32, default=NOT_SPECIFIED, choices=GENDER_CHOICES)

    phone = models.CharField(max_length=20, blank=True, default='')
    address = models.TextField(blank=True, default='')
    city = models.CharField(blank=True, default='', max_length=128)
    state = models.CharField(blank=True, default='', max_length=128)
    country = models.CharField(blank=True, default='', max_length=128)
    zip_code = models.CharField(blank=True, default='', max_length=12)

    joining_date = models.DateField(blank=True, null=True)
    leaving_date = models.DateField(blank=True, null=True)

    is_student = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    REQUIRED_FIELDS = ['first_name', 'last_name', 'email']

    def __str__(self):
        return self.username


class Student(BaseModel):
    """Creating student model."""

    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='student')
    standard = models.IntegerField(choices=SATANDARD_CHOICE)
    division = models.CharField(max_length=32, choices=DIVISION_CHOICE)
    rollnumber = models.IntegerField(blank=True, null=True)
    admission_number = models.IntegerField(blank=True, null=True)
    register_number = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.user.username


class Specification(BaseModel):
    name = models.CharField(blank=True, default='', max_length=200)

    def __str__(self):
        return self.name


class Teacher(BaseModel):
    """Creating teacher model."""

    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='teacher'
    )
    qualification = models.CharField(
        max_length=64, default=OTHER, choices=COURSE_TYPE_CHOICES
    )
    total_experience = models.PositiveIntegerField(
        blank=True, null=True, db_index=True
    )
    subject = models.ManyToManyField(Specification, blank=True)
    remarks = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.user.username

accounts/forms.py
"""Django form for model."""

from django import forms
from django.db.models import Q

from accounts.models import Student, Teacher, User


class StudentForm(forms.ModelForm):
    """Restrict one to one user model drop down list."""

    class Meta:
        model = Student
        fields = ('user', 'standard', 'division', 'rollnumber', 'admission_number', 'register_number')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].queryset = User.objects.filter(Q(teacher__isnull=True) & Q(student__isnull=True))


class TeacherForm(forms.ModelForm):
    """Restrict one to one user model drop down list."""

    class Meta:
        model = Teacher
        fields = ('user', 'qualification', 'total_experience', 'subject', 'remarks')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].queryset = User.objects.filter(Q(teacher__isnull=True) & Q(student__isnull=True))


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email', 'username', 'password', 'profile_picture',
            'birth_date', 'age', 'gender', 'phone', 'address', 'city', 'state',
            'country', 'zip_code', 'joining_date', 'leaving_date', 'is_student', 'is_staff', 'is_superuser'
        )


# class ProductCreateView(LoginRequiredMixin, CreateView):
#     model = Product
#     template_name = 'brand/product-create.html'
#     fields = '__all__'

#     def get_form(self, form_class=None):
#         form = super().get_form(form_class=None)
#         form.fields['project'].queryset = form.fields['project'].queryset.filter(owner_id=self.request.user.id)
#         return form

accounts/views.py
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic

from accounts.models import Teacher, Student, User
from accounts.forms import StudentForm, TeacherForm, UserUpdateForm


class UserCreationView(LoginRequiredMixin, UserPassesTestMixin, generic.CreateView):
    """Create accounts using generic view."""

    template_name = 'accounts/register.html'
    model = User
    fields = (
        'first_name', 'last_name', 'email', 'username', 'password', 'profile_picture',
        'birth_date', 'age', 'gender', 'phone', 'address', 'city', 'state',
        'country', 'zip_code', 'joining_date', 'leaving_date', 'is_student', 'is_staff', 'is_superuser'
    )
    student_success_url = reverse_lazy('accounts:student')
    teacher_success_url = reverse_lazy('accounts:teacher')

    def form_valid(self, form):
        user = User.objects.create_user(**form.cleaned_data)
        if user.is_student is True:
            return redirect(self.student_success_url)
        else:
            return redirect(self.teacher_success_url)

    def test_func(self):
        """
        is testing as super accounts

        :return: self.request.accounts.is_superuser
        """
        return self.request.user.is_superuser


class StudentCreationView(LoginRequiredMixin, UserPassesTestMixin, generic.CreateView):
    """Create student using generic view."""

    template_name = 'accounts/student.html'
    model = Student
    form_class = StudentForm
    success_url = reverse_lazy('accounts:student_list')

    def form_valid(self, form):
        Student.objects.create(**form.cleaned_data)
        messages.success(self.request, 'Successfully Added student')
        return redirect(self.success_url)


class TeacherCreationView(LoginRequiredMixin, UserPassesTestMixin, generic.CreateView):
    """Create teacher using generic view."""

    template_name = 'accounts/teacher.html'
    model = Teacher
    form_class = TeacherForm
    success_url = reverse_lazy('accounts:teacher_list')

    def form_valid(self, form):
        poped_subject = form.cleaned_data.pop('subject')
        print(poped_subject)
        teacher = Teacher.objects.create(**form.cleaned_data)
        for subject in poped_subject:
            teacher.subject.add(subject)
        messages.success(self.request, 'Successfully Added Teacher')
        return redirect(self.success_url)


class StudentList(generic.ListView):
    """StudentList is using to the list Student using ListView."""

    model = Student
    template_name = 'accounts/student_list.html'
    context_object_name = 'students'


class TeacherList(generic.ListView):
    """TeacherList is using to the list Teacher using ListView."""

    model = Teacher
    template_name = 'accounts/teacher_list.html'
    context_object_name = 'teachers'


class StudentDetail(generic.DetailView):
    """StudentDetail is using to display the student profile."""

    model = Student
    template_name = 'accounts/student_detail.html'
    context_object_name = 'student_profile'


class TeacherDetail(generic.DetailView):
    """TeacherDetail is using to display the teacher profile."""

    model = Teacher
    template_name = 'accounts/teacher_detail.html'
    context_object_name = 'teacher_profile'


class StudentUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    """Using UpdateView to update the user details."""

    # model = User
    # fields = ('first_name', 'last_name', 'username', 'email', 'password', 'is_superuser', 'is_staff')
    # template_name = 'login/user_update.html'
    # success_url = reverse_lazy('login:home')

    template_name = 'accounts/student_update.html'
    model = Student
    form_class = StudentForm
    success_url = reverse_lazy('accounts:student_update')

    def form_valid(self, form):
        Student.objects.update(**form.cleaned_data)
        messages.success(self.request, 'Successfully updated student')
        return redirect(self.success_url)

    def test_func(self):
        """
        This test function is using to user is superuser

        :return: self.request.user.is_superuser
        """
        return self.request.user.is_superuser


class TeacherUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    """Using UpdateView to update the user details."""

    template_name = 'accounts/teacher_update.html'
    model = Teacher
    form_class = TeacherForm
    success_url = reverse_lazy('accounts:teacher_update')

    def form_valid(self, form):
        Teacher.objects.update(**form.cleaned_data)
        messages.success(self.request, 'Successfully updated teacher')
        return redirect(self.success_url)

    def test_func(self):
        """
        This test function is using to user is superuser

        :return: self.request.user.is_superuser
        """
        return self.request.user.is_superuser


class StudentDeleteView(generic.DeleteView):
    """Delete user from the user list."""

    model = Student
    template_name = 'accounts/student_delete.html'
    success_url = reverse_lazy('accounts:student_list')


class TeacherDeleteView(generic.DeleteView):
    """Delete user from the user list."""

    model = Teacher
    template_name = 'accounts/teacher_delete.html'
    success_url = reverse_lazy('accounts:teacher_list')


class StudentUpdateNewView(generic.View):
    """Update student model with user model."""
    
    decorators = [login_required]

    @method_decorator(decorators)
    def put(self, request, id=None):
        context = {}
        student = get_object_or_404(Student, id=id)
        user = get_object_or_404(User, id=student.user.id)
        user_form = UserUpdateForm(request.POST, instance=user)
        student_form = StudentForm(request.POST, instance=student)

        if user_form.is_valid():
            get_user = user_form.save(commit=False)
            if student_form.is_valid():
                student_form.save(user=get_user.id, commit=False)
        context = {'user_form': user_form, 'student_form': student_form}
        return render(request, 'accounts/student_new_update.html', context)

accounts/templates/accounts/contact.html
{% extends "base.html" %}

{% block title %}Register{% endblock title %}
{% block content %}
{% load static %}
<div class="container">
	<h4 class="mt-3 text-center">Contact Us</h4>
    <div class="row">
      	<div class="col-md-12 col-lg-8 mb-5">
            <form action="#" class="p-5 bg-white">

              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="fullname">Full Name</label>
                  <input type="text" id="fullname" class="form-control" placeholder="Full Name">
                </div>
              </div>
              <div class="row form-group">
                <div class="col-md-12">
                  <label class="font-weight-bold" for="email">Email</label>
                  <input type="email" id="email" class="form-control" placeholder="Email Address">
                </div>
              </div>


              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="phone">Phone</label>
                  <input type="text" id="phone" class="form-control" placeholder="Phone #">
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12">
                  <label class="font-weight-bold" for="message">Message</label> 
                  <textarea name="message" id="message" cols="30" rows="5" class="form-control" placeholder="Say hello to us"></textarea>
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12">
                  <input type="submit" value="Send Message" class="btn btn-primary text-white px-4 py-2">
                </div>
              </div>
            </form>
      	</div>

      	<div class="col-lg-4">
            <div class="p-4 mb-3 bg-white">
              <h3 class="h5 text-black mb-3">Contact Info</h3>
              <p class="mb-0 font-weight-bold">Address</p>
              <p class="mb-4">203 Fake St. Mountain View, San Francisco, California, USA</p>

              <p class="mb-0 font-weight-bold">Phone</p>
              <p class="mb-4"><a href="#">+1 232 3235 324</a></p>

              <p class="mb-0 font-weight-bold">Email Address</p>
              <p class="mb-0"><a href="#">youremail@domain.com</a></p>

            </div>
            
            
        </div>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/login.html
{% load static %}

<html dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <style>
        label {
            color: white;
            font-size: 20px;
        }
    </style>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="../../assets/images/favicon.png">
    <title>Neptune</title>
     <link rel="stylesheet" href="{% static 'material-design-iconic-font/css/materialdesignicons.min.css' %}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body>
    <div class="main-wrapper">
        <!-- ============================================================== -->
        <!-- Preloader - style you can find in spinners.css -->
        <!-- ============================================================== -->
        <div class="preloader">
            <div class="lds-ripple">
                <div class="lds-pos"></div>
                <div class="lds-pos"></div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- Preloader - style you can find in spinners.css -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Login box.scss -->
        <!-- ============================================================== -->
        <div class="auth-wrapper d-flex no-block justify-content-center align-items-center bg-dark">
            <div class="auth-box bg-dark border-top border-secondary">
                <div id="loginform">
                    {% include 'accounts/_alerts.html' %}
                    <div class="text-center p-t-20 p-b-20">
                        <!--<span class="db"><img src="../../assets/images/logo.png" alt="logo" /></span>-->
                        <label>Neptune</label>
                    </div>
                    <!-- Form -->
                    <form class="form-horizontal m-t-20" action="{% url 'accounts:login' %}" id="loginform" method="POST">
                   {% csrf_token %}
                        <div class="row p-b-30">
                            <div class="col-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text bg-success text-white" id="basic-addon1"><i class="mdi mdi-account"></i></span>
                                    </div>
                                    <input type="text" name="username" class="form-control form-control-lg" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1" required="">
                                </div>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text bg-warning text-white" id="basic-addon2"><i class="mdi mdi-grease-pencil"></i></span>
                                    </div>
                                    <input type="password" name="password" class="form-control form-control-lg" placeholder="Password" aria-label="Password" aria-describedby="basic-addon1" required="">
                                </div>
                            </div>
                        </div>
                        <div class="row border-top border-secondary">
                            <div class="col-12">
                                <div class="form-group">
                                    <div class="text-center p-t-20">
                                        <!--<button class="btn btn-info" id="to-recover" type="button"><i class="fa fa-lock m-r-5"></i> Lost password?</button>-->
                                        <button class="btn btn-success" type="submit">Login</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div id="recoverform">
                    <div class="text-center">
                        <span class="text-white">Enter your e-mail address below and we will send you instructions how to recover a password.</span>
                    </div>
                    <div class="row m-t-20">
                        <!-- Form -->
                        <form class="col-12" action="index.html">
                            <!-- email -->
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text bg-danger text-white" id="basic-addon1"><i class="ti-email"></i></span>
                                </div>
                                <input type="text" class="form-control form-control-lg" placeholder="Email Address" aria-label="Username" aria-describedby="basic-addon1">
                            </div>
                            <!-- pwd -->
                            <div class="row m-t-20 p-t-20 border-top border-secondary">
                                <div class="col-12">
                                    <a class="btn btn-success" href="#" id="to-login" name="action">Back To Login</a>
                                    <button class="btn btn-info float-right" type="button" name="action">Recover</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- Login box.scss -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper scss in scafholding.scss -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper scss in scafholding.scss -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right Sidebar -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right Sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- All Required js -->
    <!-- ============================================================== -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- ============================================================== -->
    <!-- This page plugin js -->
    <!-- ============================================================== -->
    <script>

    $('[data-toggle="tooltip"]').tooltip();
    $(".preloader").fadeOut();
    // ==============================================================
    // Login and Recover Password
    // ==============================================================
    $('#to-recover').on("click", function() {
        $("#loginform").slideUp();
        $("#recoverform").fadeIn();
    });
    $('#to-login').click(function(){

        $("#recoverform").hide();
        $("#loginform").fadeIn();
    });
    </script>

</body>

</html>

accounts/templates/accounts/password-reset-complete.html
{% extends 'base.html' %}
{% block content %}
    <P>Your password has been changed successfully. </P>
    <a type="link" href="{% url 'accounts:login' %}">login to your account</a>
{% endblock content %}

accounts/templates/accounts/password-reset-confirm.html
{% extends 'base.html' %}
{% block content %}
    {% if validlink %}
        <h2>Reset your password</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Reset password</button>
        </form>
    {% else %}
        <p>May be the link is invalid or session failed</p>
        <p>Please request a new password reset</p>
    {% endif %}
{% endblock content %}

accounts/templates/accounts/password-reset.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Confirm email">
    </form>
{% endblock %}

accounts/templates/accounts/password_change_done.html
{% extends 'base.html' %}
{% block content %}
<p> Your password is changed, you need login your account </p>
<a class="btn btn-success" href="{% url 'accounts:login' %}">login</a>
{% endblock %}

accounts/templates/accounts/password_change_form.html
{% extends 'base.html' %}

{% block content %}
<div  class="card">
<div  class="card-body">
<h4  class="card-title"> Change your password</h4>

<form  method="post">
{% csrf_token %}
{{ form.as_p }}

<button  type="submit"  class="btn btn-success">Change password </button>
</form>
</div>
</div>
{% endblock content %}

accounts/templates/accounts/student_list.html
{% extends "base.html" %}

{% block title %}Student List{% endblock title %}
{% block content %}
<style>
	[role="row"] {
		text-transform: capitalize;
	}
</style>
<div class="container">
	<br>
	<h4 class="card-title mt-3 text-center">Student</h4>
	<hr>
	<!-- Alerts -->
	{% include 'accounts/_alerts.html' %}
	{% csrf_token %}
	<table id="example" class="table table-striped table-bordered" style="width:100%">
		<thead>
			<tr>
				<th>Admission Number</th>
				<th>Student</th>
				<th>Standard</th>
				<th>Register Number</th>
				<th>Update</th>
				<th>Delete</th>
			</tr>
		</thead>
		{% for u in students %}
		<tr>
			<td> {{ u.admission_number }} </td>
			<td> <a href="{% url 'accounts:student_detail' pk=u.pk %}"> {{ u.user.get_full_name }} </a> </td>
			<td> {{ u.standard }} </td>
			<td> {{ u.register_number }} </td>
			<td> <a href="{% url 'accounts:student_update' pk=u.pk %}"> Update student details </a></td>
			<td> <a href="{% url 'accounts:student_delete' pk=u.pk %}"> Delete </a> </td>
		</tr>
		{% endfor %}
	</table>
</div>
{% endblock content %}
{% block scripts %}
{% load static %}
<link rel="stylesheet" href="{% static 'accounts/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'accounts/css/buttons.bootstrap4.min.css' %}">

<script type="text/javascript" src="{% static 'accounts/js/datatables/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'accounts/js/datatables/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'accounts/js/listing.js' %}"></script>
{% endblock scripts %}

accounts/templates/accounts/teacher_list.html
{% extends "base.html" %}

{% block title %} Teacher List {% endblock title %}
{% block content %}
<style>
	[role="row"] {
		text-transform: capitalize;
	}
</style>
<div class="container">
	<br>
	<h4 class="card-title mt-3 text-center">Teachers</h4>
	<hr>
	<!-- Alerts -->
	{% include 'accounts/_alerts.html' %}
	{% csrf_token %}
	<table id="example" class="table table-striped table-bordered" style="width:100%">
		<thead>
			<tr>
				<!-- <th>SI.no.</th> -->
				<th>Teacher</th>
				<th>Course</th>
				<th>Starts from</th>
				<th>Update</th>
				<th>Delete</th>
			</tr>
		</thead>
		{% for u in teachers %}
		<tr>
			<td> <a href="{% url 'accounts:teacher_detail' pk=u.pk %}"> {{ u.user.get_full_name }} </a> </td>
			<td> {% for sub in u.subject.all %} {{ sub }} {% endfor %} </td>
			<td> {{ u.user.joining_date }} </td>
			<td> <a href="{% url 'accounts:teacher_update' pk=u.pk %}"> Update teacher details </a></td>
			<td> <a href="{% url 'accounts:teacher_delete' pk=u.pk %}"> Delete </a> </td>
		</tr>
		{% endfor %}
	</table>
</div>
{% endblock content %}
{% block scripts %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'css/buttons.bootstrap4.min.css' %}">

<script type="text/javascript" src="{% static 'js/datatables/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/datatables/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'js/listing.js' %}"></script>
{% endblock scripts %}

accounts/templates/accounts/user_update.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn_success" value="Update">
    </form>
    <script>
        $(document).ready(() =>{
            $("#id_password").attr('type', 'password');
            });
    </script>
{% endblock %}